version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: Running linter
          command: |
            sudo chown circleci:circleci /go/bin
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0            
            make lint

      - run:
          name: Running with test coverage and send to codecov
          command: |
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- ./... -cover -race -mod=vendor -coverprofile=coverage.txt -covermode=atomic
            export CODECOV_TOKEN="b10270e6-8609-4707-88f1-57c904378989"
            bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
