version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: Prerequisites
          command: |
            mkdir -p $TEST_RESULTS
            sudo chown circleci:circleci /go/bin
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

      - run:
          name: Running CI
          command: |
            make ci

      - run:
          name: Upload test results and code coverage
          command: |
            mv gotestsum-report.xml ${TEST_RESULTS}
            export CODECOV_TOKEN="b10270e6-8609-4707-88f1-57c904378989"
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /tmp/test-results
