version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: "zookeeper"
    expose:
      - "2181"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:6.0.0
    hostname: "kafka"
    expose:
      - "9092"
      - "29092"
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  localstack:
    image: localstack/localstack:0.12.0
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=sqs,sns
      - LOCALSTACK_DEBUG=1
      - LOCALSTACK_DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
