// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: examples/greeter.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_examples_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_examples_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HelloRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_examples_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_examples_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_greeter_proto protoreflect.FileDescriptor

const file_examples_greeter_proto_rawDesc = "" +
	"\n" +
	"\x16examples/greeter.proto\x12\bexamples\"J\n" +
	"\fHelloRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x89\x01\n" +
	"\aGreeter\x12:\n" +
	"\bSayHello\x12\x16.examples.HelloRequest\x1a\x14.examples.HelloReply\"\x00\x12B\n" +
	"\x0eSayHelloStream\x12\x16.examples.HelloRequest\x1a\x14.examples.HelloReply\"\x000\x01B%Z#github.com/beatlabs/patron/examplesb\x06proto3"

var (
	file_examples_greeter_proto_rawDescOnce sync.Once
	file_examples_greeter_proto_rawDescData []byte
)

func file_examples_greeter_proto_rawDescGZIP() []byte {
	file_examples_greeter_proto_rawDescOnce.Do(func() {
		file_examples_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_greeter_proto_rawDesc), len(file_examples_greeter_proto_rawDesc)))
	})
	return file_examples_greeter_proto_rawDescData
}

var file_examples_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: examples.HelloRequest
	(*HelloReply)(nil),   // 1: examples.HelloReply
}
var file_examples_greeter_proto_depIdxs = []int32{
	0, // 0: examples.Greeter.SayHello:input_type -> examples.HelloRequest
	0, // 1: examples.Greeter.SayHelloStream:input_type -> examples.HelloRequest
	1, // 2: examples.Greeter.SayHello:output_type -> examples.HelloReply
	1, // 3: examples.Greeter.SayHelloStream:output_type -> examples.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_greeter_proto_init() }
func file_examples_greeter_proto_init() {
	if File_examples_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_greeter_proto_rawDesc), len(file_examples_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_greeter_proto_goTypes,
		DependencyIndexes: file_examples_greeter_proto_depIdxs,
		MessageInfos:      file_examples_greeter_proto_msgTypes,
	}.Build()
	File_examples_greeter_proto = out.File
	file_examples_greeter_proto_goTypes = nil
	file_examples_greeter_proto_depIdxs = nil
}
