name: E2E example folder
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Running examples E2E test folder
        run: make -B examples
