name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: Lint and fmt check
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Linting and fmt check
        run: make lint

  build:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Start dependencies
        run: make deps-start

      - name: Running CI
        run: make ci

      - name: Convert coverage file to lcov
        run: |
          GO111MODULE=off go get -u github.com/jandelgado/gcov2lcov
          $(go env GOPATH)/bin/gcov2lcov -infile=coverage.txt -outfile=coverage.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
